when:
  branch: main
  event: [push, manual]

steps:
  install:
    image: node:20
    commands:
      - npm ci

  check:
    image: node:20
    commands:
      - npx svelte-check --tsconfig ./tsconfig.json

  release:
    image: node:20
    environment:
      NPM_TOKEN:
        from_secret: npm_token
    commands:
      - npm run build
      - npm version patch --no-git-tag-version
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - npm publish --access public
